FROM python:3.8-slim-buster

WORKDIR /app

# Copy requirements and install dependencies
COPY backend/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend code
COPY backend/ .

# Run your backend
CMD ["python", "app.py"]
